dist: xenial
sudo: required
language: python
python:
  - 2.7
services:
- docker

install:
  - pip install pyyaml flake8 flake8-import-order
  - apt-get install yamllint

script:
  - yamllint playbooks/.
  - yamllint roles/.
