dist: xenial
sudo: required
language: python
python:
  - 2.7
services:
- docker

install:
  - pip install pyyaml flake8 flake8-import-order
  - sudo apt-get install yamllint

script:
  - bash yamlint.sh
