---
- name: Setup Master Node
  hosts: "{{ hostname | default('127.0.0.1') }}"
  sudo: yes
  gather_facts: false
  vars_files:
      - ../group_vars/all
  tasks:
#  - name: Update repositories cache and install aptitude required for apt-get upgrade
#    apt: name={{ item }} state=latest update_cache=yes
#    with_items: "{{ packages_to_be_installed }}"

#  - name: upgrade packages
#    apt: upgrade=yes

  - name: Comment Configurations in dhcpd.conf
    replace: dest="/var/tmp/dhcpd.conf" regexp="^option domain-name" replace="# option domain-name"

  - name: Update dhcpd.conf Config File
    blockinfile:
      dest: /var/tmp/dhcpd.conf
      block: |
        subnet {{ subnet | default('192.168.2.0') }} netmask {{ netmask | default('255.255.255.0') }} {
                range {{ start_range | default('192.168.2.100') }} {{ end_range | default('192.168.2.200') }};
                option broadcast-address {{ broadcast_address | default('192.168.2.255') }};
                option domain-name-servers {{ domain_name_servers | default('8.8.8.8') }};
                option routers {{ routers | default('192.168.2.1') }};
                max-lease-time {{ max_lease_time | default('7200') }};
                option domian-name {{ domian_name | default('raspi') }};
        }
